import { Character } from './types';

// NOTE: This is a simplified representation. The full derived data will be generated by the engine on load.
export const testDummies: Character[] = [
  {
    id: 'sorcadin-dummy-01',
    name: 'Seraphina',
    level: 12,
    classes: [
      { id: 'paladin', level: 6, subclassId: 'oath-of-vengeance' },
      { id: 'sorcerer', level: 6, subclassId: 'draconic-bloodline' }
    ],
    heritage: {
      isCustom: false,
      ancestries: [],
      resolvedHeritage: {
        id: 'aasimar-protector',
        name: 'Protector Aasimar',
        source: 'VGM',
        iconUrl: 'https://picsum.photos/seed/aasimar-protector/64/64',
        traits: []
      }
    },
    background: {
      id: 'noble',
      name: 'Noble',
      source: 'PHB',
      feature: { name: 'Position of Privilege', description: '' },
      traits: [],
      startingGold: 25
    },
    abilityScores: {
      STRENGTH: { base: 15, bonus: 0 },
      DEXTERITY: { base: 8, bonus: 0 },
      CONSTITUTION: { base: 14, bonus: 0 },
      INTELLIGENCE: { base: 8, bonus: 0 },
      WISDOM: { base: 10, bonus: 1 },
      CHARISMA: { base: 14, bonus: 2 }
    },
    feats: [{ featId: 'war-caster', source: 'asi-feat-4-paladin', choices: {} }],
    selectedProficiencies: [],
    selectedFightingStyles: [{ id: 'dueling', source: 'paladin-fighting-style-2' }],
    selectedInvocations: [],
    selectedMetamagic: ['quickened-spell', 'twinned-spell'],
    hp: 0, currentHp: 0, tempHp: 0, ac: 0, initiative: 0, speed: 0,
    flyingSpeed: 0, swimmingSpeed: 0, climbingSpeed: 0,
    encumbranceStatus: 'none', stealthDisadvantage: false,
    passivePerception: 0, passiveInvestigation: 0,
    pendingChoices: [],
    inventory: [], equippedItems: {},
    money: { pp: 0, gp: 10, ep: 0, sp: 0, cp: 0 },
    backstoryDetails: { personality: 'Regal and driven by a divine mandate for justice.', ideals: 'The wicked must be punished, no matter their station.', bonds: 'My celestial guide whispers truths to me.', flaws: 'I can be blinded by my righteous fury.', backstory: '', notes: '' },
    physicalCharacteristics: { age: '28', height: '6\'1"', weight: '170 lbs', eyes: 'Silver', skin: 'Fair', hair: 'Platinum Blonde', gender: 'Female', alignment: 'Lawful Good', faith: 'Tyr' },
    characterPortraitUrl: '',
    preparedSpells: [], knownSpells: [], spellbook: [], mysticArcanum: {},
    attunedItemIds: [], knownInfusions: [], infusedItems: [],
    hitDice: {}, expendedSpellSlots: {}, expendedPactSlots: 0, innateSpellUses: {}, 
    featureUses: {},
    startingEquipmentGranted: true, activeConcentration: undefined,
    concentrationSaveDc: null, activeEffects: [],
    deathSaves: { successes: 0, failures: 0 },
    uncannyDodgePrompt: null, interactionPrompt: null, summonChoicePrompt: null, activeCompanions: [],
    experimentalElixirs: [], arcaneWard: { current: 0, max: 0 }, wildShapeForm: null,
    wildShapeEquipmentOption: 'merge', symbioticEntityActive: false,
    activeStates: [], exhaustionLevel: 0, turnData: { attacked: false, tookDamage: false },
    usedSneakAttackThisTurn: false, resources: [],
    actionEconomy: { action: true, bonusAction: true, reaction: true },
    activeHuntersMarkTargetId: undefined,
    activeVowOfEnmityTargetId: undefined,
  },
  {
    id: 'fighterbarian-dummy-01',
    name: 'Grak the Breaker',
    level: 8,
    classes: [
      { id: 'fighter', level: 5, subclassId: 'battle-master' },
      { id: 'barbarian', level: 3, subclassId: 'path-of-the-berserker' }
    ],
    heritage: {
      isCustom: false,
      ancestries: [],
      resolvedHeritage: {
        id: 'half-orc',
        name: 'Half-Orc',
        source: 'PHB',
        iconUrl: 'https://picsum.photos/seed/half-orc/64/64',
        traits: []
      }
    },
    background: {
      id: 'soldier',
      name: 'Soldier',
      source: 'PHB',
      feature: { name: 'Military Rank', description: '' },
      traits: [],
      startingGold: 10
    },
    abilityScores: {
      STRENGTH: { base: 15, bonus: 2 },
      DEXTERITY: { base: 12, bonus: 0 },
      CONSTITUTION: { base: 14, bonus: 1 },
      INTELLIGENCE: { base: 8, bonus: 0 },
      WISDOM: { base: 10, bonus: 0 },
      CHARISMA: { base: 10, bonus: 0 }
    },
    feats: [{ featId: 'great-weapon-master', source: 'asi-feat-4-fighter', choices: {} }],
    selectedProficiencies: [],
    selectedFightingStyles: [{ id: 'great-weapon-fighting', source: 'fighter-style-1' }],
    selectedInvocations: [],
    selectedMetamagic: [],
    fighter: {
      selectedManeuvers: ['riposte', 'precision-attack', 'menacing-attack']
    },
    hp: 0, currentHp: 0, tempHp: 0, ac: 0, initiative: 0, speed: 0,
    flyingSpeed: 0, swimmingSpeed: 0, climbingSpeed: 0,
    encumbranceStatus: 'none', stealthDisadvantage: false,
    passivePerception: 0, passiveInvestigation: 0,
    pendingChoices: [],
    inventory: [], equippedItems: {},
    money: { pp: 0, gp: 10, ep: 0, sp: 0, cp: 0 },
    backstoryDetails: { personality: 'Gruff and straightforward. Solves problems with his axe.', ideals: 'Strength is the only true virtue.', bonds: 'My warband is my family.', flaws: 'I am quick to anger and slow to trust.', backstory: '', notes: '' },
    physicalCharacteristics: { age: '35', height: '6\'5"', weight: '240 lbs', eyes: 'Black', skin: 'Gray', hair: 'Black', gender: 'Male', alignment: 'Chaotic Neutral', faith: 'Tempus' },
    characterPortraitUrl: '',
    preparedSpells: [], knownSpells: [], spellbook: [], mysticArcanum: {},
    attunedItemIds: [], knownInfusions: [], infusedItems: [],
    hitDice: {}, expendedSpellSlots: {}, expendedPactSlots: 0, innateSpellUses: {}, 
    featureUses: {},
    startingEquipmentGranted: true, activeConcentration: undefined,
    concentrationSaveDc: null, activeEffects: [],
    deathSaves: { successes: 0, failures: 0 },
    uncannyDodgePrompt: null, interactionPrompt: null, summonChoicePrompt: null, activeCompanions: [],
    experimentalElixirs: [], arcaneWard: { current: 0, max: 0 }, wildShapeForm: null,
    wildShapeEquipmentOption: 'merge', symbioticEntityActive: false,
    activeStates: [], exhaustionLevel: 0, turnData: { attacked: false, tookDamage: false },
    usedSneakAttackThisTurn: false, resources: [],
    actionEconomy: { action: true, bonusAction: true, reaction: true },
    activeHuntersMarkTargetId: undefined,
    activeVowOfEnmityTargetId: undefined,
  }
];